import type { Metadata } from "next";
import "./globals.css";
import Providers from "../ui/providers";



export const metadata: Metadata = {
  title: "Notes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en" suppressHydrationWarning>
      <body className={`h-full bg-neutral-100 flex flex-col dark:bg-neutral-800`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
